spring:
    #代码生成配置
    codegen:
        config:
            #业务/功能模块名称
            product:
                #领域对象配置
                domain:
                    #领域对象公共配置
                    domainCommons:
                        #输出目标源码上的注释作者
                        targetAuthor: AutoCodeGenerator
                        #输出目标源码上的注释版本
                        targetVersion: 1.0.0
                        #领域对象源码输出项目目录
                        targetProject: src/main/java
                        #领域对象源码输出公共父包,其下约定有子包：model、enums
                        targetPackage: com.penglecode.codeforce.samples.product.domain.model
                        #领域对象运行时数据源名称
                        runtimeDataSource: product
                        #领域对象内省数据源名称
                        introspectDataSource: product
                        #领域对象数据库内省配置
                        introspectConfig:
                            #强制将数据库中的日期时间字段映射为String类型? 默认为Java8日期/时间对象
                            forceDateTimeAsString: true
                            #强制将数据库中的INT(1)/TINYINT(1)/NUMBER(1)等字段映射为Boolean类型?
                            forceNumber1AsBoolean: true
                            #强制将数据库中的浮点型字段映射为Double类型? 默认为BigDecimal
                            forceDecimalNumericAsDouble: true
                        #默认的创建时间列名
                        defaultCreateTimeColumn: create_time
                        #默认的修改时间列名
                        defaultUpdateTimeColumn: update_time
                        #领域枚举定义
                        domainEnums:
                            #使用已存在的枚举
                          - domainEnumName: ProductTypeEnum
                            domainEnumTitle: 商品类型枚举
                            #领域枚举Class(如果指定了domainEnumClass则表示当前领域枚举是已经存在的并不需要生成代码)
                            domainEnumClass: com.penglecode.codeforce.samples.product.domain.enums.ProductTypeEnum
                            domainEnumCodeField: {fieldType: java.lang.Integer, fieldName: typeCode}
                            domainEnumNameField: {fieldType: java.lang.String, fieldName: typeName}
                            #定义新的枚举类型
                          - domainEnumName: ProductAuditStatusEnum
                            domainEnumTitle: 商品审核状态枚举
                            domainEnumCodeField: {fieldType: java.lang.Integer, fieldName: statusCode}
                            domainEnumNameField: {fieldType: java.lang.String, fieldName: statusName}
                            domainEnumValues: {WAIT_AUDIT: [0, '待审核'], AUDIT_PASSED: [1, '审核通过'], AUDIT_UNPASSED: [2, '审核不通过']}
                            #定义新的枚举类型
                          - domainEnumName: ProductOnlineStatusEnum
                            domainEnumTitle: 商品上下架状态枚举
                            domainEnumCodeField: {fieldType: java.lang.Integer, fieldName: statusCode}
                            domainEnumNameField: {fieldType: java.lang.String, fieldName: statusName}
                            domainEnumValues: {OFFLINE: [0, '已下架'], ONLINE: [1, '已上架']}
                        #全局性的类型映射集合,以便后续省去使用带包名的全名称配置引用
                        globalTypes:
                            NamedDatabase: org.springframework.boot.autoconfigure.mds.NamedDatabase
                    #领域实体对象列表
                    domainEntities:
                        #领域实体对象类名
                      - domainEntityName: ProductBaseInfo
                        #领域实体对应的数据库表名
                        domainEntityTable: t_product_base_info
                        #领域实体对象中文名称
                        domainEntityTitle: 商品基本信息
                        #领域实体对象别名(在方法命名、参数/变量命名、URL命名时使用)
                        domainEntityAlias: ProductBase
                        #领域实体对象运行时数据源
                        runtimeDataSource: product
                        #领域实体对象内省数据库配置
                        introspectConfig:
                            #考虑到分库分表需要在此增设实际自省表表名(如果为空则取domainEntityTable)
                            #introspectTableName: t_product_base_info
                            #强制将数据库中的日期时间字段映射为String类型? 否则为Java8日期/时间对象
                            forceDateTimeAsString: true
                            #强制将数据库中的INT(1)/TINYINT(1)/NUMBER(1)等字段映射为Boolean类型?
                            forceNumber1AsBoolean: true
                            #强制将数据库中的浮点型字段映射为Double类型? 否则为BigDecimal
                            forceDecimalNumericAsDouble: true
                        #领域对象的所有列,其中queryOperator支持eq,like|likeLeft|likeRight,gt|lt|gte|lte,in等
                        domainEntityColumns:
                          - {columnName: 'product_id', columnTitle: '商品ID', idColumn: true}
                          - {columnName: 'product_name', columnTitle: '商品名称', columnOnUpsert: true, validateOnUpsert: true, queryOperator: 'likeRight'}
                          - {columnName: 'product_url', columnTitle: '商品详情URL', columnOnUpsert: true, validateOnUpsert: true}
                          - {columnName: 'product_tags', columnTitle: '商品标签', columnOnUpsert: true, validateOnUpsert: true, queryOperator: 'like'}
                          - {columnName: 'product_type', columnTitle: '商品类型', columnOnUpsert: true, validateOnUpsert: true, javaType: 'java.lang.Integer', queryOperator: 'eq', decodeEnumType: 'ProductTypeEnum'}
                          - {columnName: 'audit_status', columnTitle: '审核状态', columnOnUpsert: true, validateOnUpsert: true, javaType: 'java.lang.Integer', queryOperator: 'in', decodeEnumType: 'ProductAuditStatusEnum'}
                          - {columnName: 'online_status', columnTitle: '上下架状态', columnOnUpsert: true, validateOnUpsert: true, javaType: 'java.lang.Integer', queryOperator: 'eq', decodeEnumType: 'ProductOnlineStatusEnum'}
                          - {columnName: 'shop_id', columnTitle: '所属店铺ID', columnOnInsert: true, validateOnInsert: true, queryOperator: 'eq'}
                          - {columnName: 'remark', columnTitle: '商品备注', columnOnUpsert: true}
                          - {columnName: 'create_time', columnTitle: '创建时间', columnOnInsert: true, validateOnInsert: true, queryOperator: 'gte,lte', selectClause: "DATE_FORMAT({name}, '%Y-%m-%d %T')"}
                          - {columnName: 'update_time', columnTitle: '最近更新时间', columnOnUpsert: true, validateOnUpsert: true, selectClause: "DATE_FORMAT({name}, '%Y-%m-%d %T')"}
                      - domainEntityName: ProductExtraInfo
                        domainEntityTable: t_product_extra_info
                        domainEntityTitle: 商品额外信息
                        domainEntityAlias: ProductExtra
                        domainEntityColumns:
                          - {columnName: 'product_id', columnTitle: '商品ID', idColumn: true}
                          - {columnName: 'product_details', columnTitle: '商品详情', columnOnUpsert: true, validateOnUpsert: true}
                          - {columnName: 'product_specifications', columnTitle: '商品规则参数', columnOnUpsert: true}
                          - {columnName: 'product_services', columnTitle: '商品服务', columnOnUpsert: true}
                          - {columnName: 'create_time', columnTitle: '创建时间', columnOnInsert: true, validateOnInsert: true, selectClause: "DATE_FORMAT({name}, '%Y-%m-%d %T')"}
                          - {columnName: 'update_time', columnTitle: '最近更新时间', columnOnUpsert: true, validateOnUpsert: true, selectClause: "DATE_FORMAT({name}, '%Y-%m-%d %T')"}
                      - domainEntityName: ProductSaleSpec
                        domainEntityTable: t_product_sale_spec
                        domainEntityTitle: 商品销售规格信息
                        domainEntityAlias: ProductSaleSpec
                        domainEntityColumns:
                          - {columnName: 'product_id', columnTitle: '商品ID', idColumn: true}
                          - {columnName: 'spec_no', columnTitle: '规格编号', idColumn: true}
                          - {columnName: 'spec_name', columnTitle: '规格名称', columnOnUpsert: true, validateOnUpsert: true}
                          - {columnName: 'spec_index', columnTitle: '规格顺序', columnOnUpsert: true, validateOnUpsert: true}
                          - {columnName: 'remark', columnTitle: '备注', columnOnUpsert: true}
                          - {columnName: 'create_time', columnTitle: '创建时间', columnOnInsert: true, validateOnInsert: true, selectClause: "DATE_FORMAT({name}, '%Y-%m-%d %T')"}
                          - {columnName: 'update_time', columnTitle: '最近更新时间', columnOnUpsert: true, validateOnUpsert: true, selectClause: "DATE_FORMAT({name}, '%Y-%m-%d %T')"}
                      - domainEntityName: ProductSaleStock
                        domainEntityTable: t_product_sale_stock
                        domainEntityTitle: 商品销售库存信息
                        domainEntityAlias: ProductSaleStock
                        domainEntityColumns:
                          - {columnName: 'product_id', columnTitle: '商品ID', idColumn: true}
                          - {columnName: 'spec_no', columnTitle: '规格编号', idColumn: true}
                          - {columnName: 'spec_name', columnTitle: '规格名称', columnOnUpsert: true, validateOnUpsert: true}
                          - {columnName: 'sell_price', columnTitle: '售价', columnOnUpsert: true, validateOnUpsert: true}
                          - {columnName: 'stock', columnTitle: '库存', columnOnUpsert: true, validateOnUpsert: true}
                          - {columnName: 'create_time', columnTitle: '创建时间', columnOnInsert: true, validateOnInsert: true, selectClause: "DATE_FORMAT({name}, '%Y-%m-%d %T')"}
                          - {columnName: 'update_time', columnTitle: '最近更新时间', columnOnUpsert: true, validateOnUpsert: true, selectClause: "DATE_FORMAT({name}, '%Y-%m-%d %T')"}

                    #领域聚合根(如果定义了聚合根，则后端会生成对应的{domainAggregateName}AppService)
                    domainAggregates:
                        #领域聚合根类名(为避免与实体对象命名冲突,聚合根统一以Aggregate结尾)
                      - domainAggregateName: ProductAggregate
                        #领域聚合根中文名称
                        domainAggregateTitle: 商品
                        #领域聚合根别名(在方法命名、参数/变量命名、URL命名时使用)
                        domainAggregateAlias: Product
                        #领域聚合根的主要实体对象名称(指向domainEntities列表中的某一个)
                        aggregateMasterEntity: ProductBaseInfo
                        #领域聚合根的从属实体对象列表
                        aggregateSlaveEntities:
                            #领域聚合根的从属实体对象(指向domainEntities列表中的某一个)
                          - aggregateSlaveEntity: ProductExtraInfo
                            #主要领域对象与从属领域对象的映射关系(支持1:1/1:N)
                            masterSlaveMapping: 'product_id:product_id=1:1'
                            #保存主要实体对象时是否也级联保存从属实体对象
                            cascadingOnUpsert: true
                            #新建主要实体对象时是否也级联新建从属实体对象
                            #cascadingOnInsert: true
                            #新建主要实体对象时是否校验从属实体对象不为空(仅在cascadingOnInsert=true时有效)
                            #validateOnInsert: true
                            #更新主要实体对象时是否也级联更新从属实体对象
                            #cascadingOnUpdate: true
                            #更新主要实体对象时是否校验从属实体对象不为空(仅在cascadingOnUpdate=true时有效)
                            #validateOnUpdate: true
                            #聚合根的从属实体对象(指向domainEntities列表中的某一个)
                          - aggregateSlaveEntity: ProductSaleSpec
                            #主要领域对象与从属领域对象的映射关系(支持1:1/1:N)
                            masterSlaveMapping: 'product_id:product_id=1:N'
                            #保存主要实体对象时是否也级联保存从属实体对象
                            cascadingOnUpsert: true
                          - aggregateSlaveEntity: ProductSaleStock
                            #主要领域对象与从属领域对象的映射关系(支持1:1/1:N)
                            masterSlaveMapping: 'product_id:product_id=1:N'
                            #保存主要实体对象时是否也级联保存从属实体对象
                            cascadingOnUpsert: true
                #Mybatis(DAL层)代码部分
                mybatis:
                    javaMapperConfig:
                        #XxxMapper.java源码输出项目目录
                        targetProject: src/main/java
                        #XxxMapper.java所在包名
                        targetPackage: com.penglecode.codeforce.samples.product.dal.mapper
                        #当前领域对象的Mapper接口上的数据库名称,默认:'@NamedDatabase("${runtimeDataSource}")'
                        mapperAnnotations: '@NamedDatabase("${runtimeDataSource}")'
                #Service代码部分
                service:
                    #领域服务代码生成配置
                    domain:
                        interfaceConfig:
                            #服务接口源码输出项目目录
                            targetProject: src/main/java
                            #服务接口所在包名
                            targetPackage: com.penglecode.codeforce.samples.product.domain.service
                        implementConfig:
                            #服务实现源码输出项目目录
                            targetProject: src/main/java
                            #服务实现所在包名
                            targetPackage: com.penglecode.codeforce.samples.product.domain.service.impl
                    #应用服务代码生成配置
                    application:
                        interfaceConfig:
                            #服务接口源码输出项目目录
                            targetProject: src/main/java
                            #服务接口所在包名
                            targetPackage: com.penglecode.codeforce.samples.product.application.service
                        implementConfig:
                            #服务实现源码输出项目目录
                            targetProject: src/main/java
                            #服务实现所在包名
                            targetPackage: com.penglecode.codeforce.samples.product.application.service.impl
                #API代码部分
                api:
                    #API接口的URL前缀(默认：/api)
                    apiUrlPrefix: /api
                    #API层的公共基础包,其下约定有子包：dto、request、response、service、controller五个子包
                    targetPackage: com.penglecode.codeforce.samples.product.api
                    #API接口客户端配置
                    clientConfig:
                        #API接口协议,FEIGN是必须的,DUBBO是可选的
                        apiProtocols: FEIGN,DUBBO
                        #API接口声明Map类型,[key=领域对象名称,value=接口方法名枚举]
                        apiProviders:
                            #ProductAggregate: CREATE,MODIFY_BY_ID,REMOVE_BY_ID,REMOVE_BY_IDS,GET_BY_ID,GET_BY_IDS,GET_BY_PAGE
                            ProductAggregate: ALL
                    #API接口实现配置
                    runtimeConfig:
                        #API接口声明Map类型,[key=领域对象名称,value=接口方法名枚举]
                        #此处出现的API接口声明将仅仅是一个Controller,并不提供RPC服务的Client接口
                        #apiProviders:
                            #ProductAggregate: CREATE,MODIFY_BY_ID,REMOVE_BY_ID,REMOVE_BY_IDS,GET_BY_ID,GET_BY_IDS,GET_BY_PAGE
                        #API接口继承父类(可以不配置)
                        apiExtendsClass: com.penglecode.codeforce.common.web.servlet.support.ServletHttpApiSupport