spring:
    #数据源配置
    datasource:
        #商品库
        product:
            username: root
            password: 123456
            url: jdbc:mysql://127.0.0.1:3306/codeforce_samples?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true&useCursorFetch=true